amp: false
asa_path: /home/abin/eeg-mlflow/eeg_analysis/secondarydata/raw/asa_electrodes.txt
batch_size: 16
d_model: 256
dataset_path: /home/abin/eeg-mlflow/eeg_analysis/secondarydata/raw
epochs: 200
grad_clip_norm: 0.5
lr: 0.0008
mask_ratio: 0.2
masking_style: mae
min_delta: 0.0001
mlflow_experiment: eeg_pretraining_mamba2_sweep_mask
mlflow_tracking_uri: mlruns
num_layers: 2
patience: 20
save_dir: /home/abin/eeg-mlflow/eeg_analysis/checkpoints
val_ratio: 0.2
window_length: 2048
