name: MLflow Tracking

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  track-experiments:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run experiments tracking
      run: |
        python run_pipeline.py process --config configs/local_config.yaml
        python run_pipeline.py train --level window --config configs/local_config.yaml
        python run_pipeline.py train --level patient --config configs/local_config.yaml